// Auto-generated by scripts/bake-versions.ts — do not edit
export const VERSIONS: Record<string, string> = {
	'@wolf-tui/react': '^1.5.0',
	'@wolf-tui/vue': '^1.5.0',
	'@wolf-tui/angular': '^1.5.0',
	'@wolf-tui/solid': '^1.5.0',
	'@wolf-tui/svelte': '^1.3.0',
	'@wolf-tui/plugin': '^1.5.0',
	'@wolf-tui/typescript-plugin': '^1.3.0',
	'@wolf-tui/core': '^1.5.0',
	'@wolf-tui/shared': '^1.5.0',
	'@wolf-tui/css-parser': '^1.5.0',
} as const
